# avers.yaml
---
- name: Creating EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tags: provisioning
  vars:
        keypair: your_keypair
        instance_type: "t2.micro"
        image: "ami-33db9803"
        group: "your_sgroup"
        region: "us-west-2"
  
  tasks:
    - name: Launch new Instance
      local_action: ec2 instance_tags="Name=instancename" group={{ group }} instance_type={{ instance_type }} image={{ image }} wait=true region={{ region }} keypair={{ keypair }}
      register: ec2

    - name: Add instance to local host group
      local_action: lineinfile dest=/etc/ansible/hosts regexp="{{ item.public_dns_name }}" insertafter="[web]" line="{{ item.public_dns_name }} ansible_ssh_private_key_file=~/.ssh/{{ keypair }}.pem"
      with_items: ec2.instances
 
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - meta: refresh_inventory

- name: Configure new instance
  hosts: web
  user: ubuntu
  sudo: yes
  gather_facts: True

  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Install required packages
      apt: name={{ item }}
      with_items:
        - zip
        - unzip
        - build-essential
        - expect
        - sockstat
        - python-pip
