- hosts: web
  remote_user: 'vagrant'
  gather_facts: no
  vars:
    number: '$web'

  tasks:

    - name: Install apache
      apt: 
        name: 'apache2' 
        state: present
        update_cache: yes

    - name: Copy new vhost file
      copy:
        src: ./configs/web.conf
        dest: /etc/apache2/sites-available/

    - name: Add test webpage
      shell: 'echo "I am server {{ number }}" >> /var/www/html/index.html'

    - name: Restart Apache
      command: 'service apache2 restart'
