- hosts: web1
  remote_user: 'vagrant'
  gather_facts: no

  tasks:

    - name: Install apache
      apt: 
        name: 'apache2' 
        state: present
        update_cache: yes

    - name: Remove default vhost
      shell: 'rm /etc/apache2/sites-available/000-default.conf'

    - name: Copy new vhost file
      copy:
        src: ./configs/000-default.conf
        dest: /etc/apache2/sites-available/

    - name: Create index.html and grant privileges for apache
      file:
        path: /var/www/html/index.html
        owner: www-data
        mode: 0755
        state: file
        
    - name: Add test webpage
      shell: 'echo "I am server 1" >> /var/www/html/index.html'
      
    - name: Restart Apache
      command: 'service apache2 restart'
