---
# Remember, leave a key empty if there is no value.  None will be a string,
# not a Python "NoneType"
client:
  hosts:
    - ip_your_elasticsearch_host
  port: 9200
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth:
  timeout: 900
  master_only: true

logging:
  loglevel: INFO
  logfile: /var/log/elasticsearch/curator.log
  logformat: json
