---
- name: Configure new jenkins instance
  hosts: 'all'
  sudo: 'yes'
  tasks:

    - name: Download Jenkins
      shell: 'wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -'

    - name: Download Jenkins
      shell: 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'

    - name: Update
      apt: update_cache=yes

    - name: Install dependencies
      apt: name='{{ item }}'
      with_items:
        - 'git'
        - 'build-essential'
        - 'openssl'
        - 'curl'
        - 'jenkins'
        - 'maven'

    - name: Restart Jenkins
      command: service jenkins restart

    - name: Add user Jenkins with ssh key
      user:
        name: jenkins
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
